formatter: markdown

settings:
  anchor: true
  hide-empty: true
  indent: true

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_AUTOMATIC_TF_DOCS -->
    {{ .Content }}
    <!-- END_AUTOMATIC_TF_DOCS -->

content: |-
  {{ .Header }}

  {{ .Requirements }}

  {{ .Providers }}

  # Examples
  main.tf
  ```hcl
  {{ include "examples/main/main.tf" }}
  ```
  outputs.tf
  ```hcl
  {{ include "examples/main/outputs.tf" }}
  ```

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}
