- name: Create Platform Delivery Group
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: "{{ '/usr/bin/python3' }}"

  tasks:
    - name: Create Group
      group:
        name: platform-delivery
        state: present
