- name: Install Apache and Check if it's running
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: "{{ '/usr/bin/python3' }}"

  tasks:
  - name: Install Apache
    ansible.builtin.yum:
      name: httpd
      state: present

  - name: Ensure Apache latest version is installed
    ansible.builtin.yum:
      name: httpd
      state: latest

  - name: Ensure Apache is running
    service: name=httpd state=started
